### ISSUE TITLE
Adopt stylelint for CSS linting

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/zoe#32]
https://stylelint.io/

We can take advantage of Prettier for formatting CSS too.

**Comment by jorgegonzalez** [comment]
Still debating whether to include CSS linting in this project, or in a new project.

If we include it in `zoe`, it will be a unique feature that sets us apart from `xo`, `standard`, and `lynt` (which are the most similar projects to `zoe`). 

However, [`stylelint`](https://packagephobia.now.sh/result?p=stylelint) is as big as `eslint`. `zoe` is currently much bigger than `xo`, `standard`, and `lynt`, and many users are loath to adding giant packages to their workflow (even though it is a `devDependency`).

**Comment by azdanov** [comment]
Can css be optional, but included? Since this is not a library, but more of a tool the size shouldn't be such a critical asset.

I think this package is geared more towards beginners, than experienced users, who already have all the needed scripts in a personal package, for example [kcd-scripts](https://github.com/kentcdodds/kcd-scripts).

As a user I love options when using a single tool, trying to orchestrate couple of linters and formaters is painful.

For example some Visual Studio Code extensions provide integration with popular tools reducing developer's cognitive load when setting up a working environment.

**Comment by jorgegonzalez** [comment]
What do you mean by optional? It can be optional in the same way that TypeScript and React are currently "optional", in that they are only processed as TypeScript or React files if they are discovered in the input paths.

**Comment by jorgegonzalez** [comment]
Do you think this feature should be included in `zoe@2.0.0`?

**Comment by azdanov** [comment]
I was thinking of dynamically adding additional features on user demand, but that's probably jumping too far ahead.

Could do a test-drive, see how everything works with css. If it's good then it's a unique feature of `zoe`.
